language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt --all -- --write-mode=diff
  - cargo test --verbose --all
notifications:
  email: false
